version: '3'
services:
  sonarqube:
    container_name: "sonarqube"
    image:  sonarqube:8-community
    restart: always
    depends_on:
      - db
    environment: 
      SONARQUBE_JDBC_URL:JDBC: postgresql://db:5543/sonarqubedb
      SONARQUBE_JDBC_URL_USERNAME: sonar
      SONARQUBE_JDBC_URL_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqubeCE/conf
      - sonarqube_data:/opt/sonarqubeCE/sonarqube_data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundle-plugins:/opt/sonarqube/lib/bundle_plugins
    ports:
      - "9000:9000"
  db:
    container_name: "postgresql"
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - /opt/postgresql:/var/lib/postgresql
      - /opt/postgresql/data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundle-plugins: